version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: Meu_Docker_MySQL
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=Meu_Docker_MySQL
    ports:
      - "3306:3306"
    volumes:
      - ./dados_mysql:/var/lib/mysql
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql